// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwgnsvjnmitfwvmprvmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Z25zdmpubWl0Znd2bXBydm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDg0ODEsImV4cCI6MjA2MTMyNDQ4MX0.75Rud18ZOjFxU9TJ6nB8M0f7tQl1Su-sqZR9vGj31BM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);